# 다이닝 코드 데이터

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

df = pd.read_csv('crawled_data/diningcode_data_crawling_seoul_20260125_1542.csv')

In [2]:
df1 = pd.read_csv('crawled_data/diningcode_data_crawling_gyeonggi_20260322_1244.csv')

In [3]:
data = pd.concat([df,df1],axis=0,ignore_index=True)

In [4]:
data = data.drop(columns=['Unnamed: 0'],axis=1)
data.shape

(19297, 15)

## Preprocessing data

In [5]:
# 다코 미식가 / user_name 분리
daco_list = dict()
name_list = list()
for i,val in enumerate(data['user_name']):
    if "다코미식가" in val:
        daco_list[i] = 1
    else:
        daco_list[i] = 0
    name_list.append(data['user_name'][i].replace('다코미식가',''))
data['daco_gourmand'] = daco_list

name_list = [name.replace('\r\n', '') for name in name_list]
name_list = [name.replace('\n', '') for name in name_list]
data['user_name'] = name_list

In [6]:
data['user_rating'] = data['user_rating'].str.replace('점','').astype(float)

In [7]:
unique_vals = data['taste'].unique()
mapping_dict = {
    unique_vals[0]:3,
    unique_vals[1]:2,
    unique_vals[2]:1
}
data['taste_enc'] = data['taste'].map(mapping_dict)
del mapping_dict, unique_vals

unique_vals = data['service'].unique()
mapping_dict = {
    unique_vals[0]:3,
    unique_vals[1]:2,
    unique_vals[2]:1
}
data['service_enc'] = data['service'].map(mapping_dict)
del mapping_dict, unique_vals

unique_vals = data['price'].unique()
mapping_dict = {
    unique_vals[0]:3,
    unique_vals[1]:2,
    unique_vals[2]:1
}
data['price_enc'] = data['price'].map(mapping_dict)
del mapping_dict, unique_vals

In [8]:
user_le = LabelEncoder()
item_le = LabelEncoder()

data['user_id'] = user_le.fit_transform(data['user_name'])
data['item_id'] = item_le.fit_transform(data['item_name'])

# User name-id mapping
user_i2n = dict(enumerate(user_le.classes_))  
user_n2i = {v: k for k, v in user_i2n.items()}

item_i2n = dict(enumerate(item_le.classes_))
item_n2i = {v: k for k, v in item_i2n.items()}

In [9]:
np.sum(data['user_name'].value_counts() > 1)

3122

In [10]:
data = data.drop_duplicates()

In [11]:
data.shape

(13944, 21)

In [13]:
data['user_query'].map(len,).sort_values(ascending=False)

4036     1019
5023     1014
5615     1008
4554     1005
8         999
         ...
17131       1
17133       1
15765       1
19295       1
19296       1
Name: user_query, Length: 13944, dtype: int64

## Project_Main (Founding Recommnedation model)
1. Baseline (DeepFM or MF model)
2. DeepCoNN + MF
3. LLM (KoBERT,Gemma) + MF model

### 1. Baseline (Matrix Factorization)

In [67]:
user_item_mat = pd.pivot_table(data=data,index='item_id',
                               columns='user_id',values='user_rating')
print('sparsity : %.4f ' % (np.count_nonzero(np.isnan(user_item_mat)) / user_item_mat.size))
print(f'user_item_mat shape : {user_item_mat.shape}')

sparsity : 0.9924
user_item_mat shape : (353, 5205)

In [69]:
mf_data = data[['user_name','item_name','user_rating']]
mf_data.columns = ['user','item','rating']

mf_train = mf_data.groupby('user').sample(frac=0.8,random_state=42)
mf_train_ind = mf_train.index
mf_test = mf_data.drop(mf_train_ind)

In [70]:
import sys
sys.path.append('../..')  # Go up two levels to reach the directory containing 'Study'

from Study.RecSys.matrixfactorization import matfac

k=10
lr=0.001
reg_param = 0.02
epochs=50

mf_model = matfac.MatrixFactorization(k,lr,reg_param,epochs)

P,Q,b_u,b_i = mf_model.fit(mf_train)
mf_pred,mf_test = mf_model.predict(mf_test)

Epoch : 0 , Loss : 4333.204973 , Rooted Loss: 65.83
Epoch : 10 , Loss : 3797.764344 , Rooted Loss: 61.63
Epoch : 20 , Loss : 3570.832885 , Rooted Loss: 59.76
Epoch : 30 , Loss : 3446.418405 , Rooted Loss: 58.71
Epoch : 40 , Loss : 3369.397120 , Rooted Loss: 58.05

In [15]:
y_pred = mf_pred
y_true = mf_test
k=10
ndcg_k = []
for user_num in y_pred['user'].unique():
    top_pred_items = y_pred.loc[(y_pred['user']==user_num)].sort_values('rating',ascending=False)
    pred_sequence = top_pred_items['item'][:k].values

    test_items = y_true.loc[y_true['user']==user_num]
    ideal_rel_score = test_items.sort_values('rating',ascending=False)[:k]['rating'].values
    rel_score = test_items.set_index('item').reindex(pred_sequence)['rating'].values
    dcg_k = np.sum((np.pow(2,rel_score) -1) / np.log2(np.arange(2,len(rel_score)+2)))
    idcg_k = np.sum((np.pow(2,ideal_rel_score) -1) / np.log2(np.arange(2,len(ideal_rel_score)+2)))
    ndcg_k.append(dcg_k / idcg_k if idcg_k>0 else 0)
np.mean(ndcg_k)

np.float64(0.991511046819293)

In [71]:
from Study.RecSys.matrixfactorization.preprocessing import precision_at_k,ndcg_at_k,recall_at_k
from sklearn.metrics import root_mean_squared_error

rmse_par = root_mean_squared_error(mf_pred['rating'].values,mf_test['rating'].values)
prec_at_k_par = precision_at_k(mf_pred,mf_test,k=10)
rec_at_k_par = recall_at_k(mf_pred,mf_test,k=10)
ndcg_at_k_par = ndcg_at_k(mf_pred,mf_test,k=10)

print(f'RMSE: {rmse_par:.4f},Precision@K: {prec_at_k_par:.4f},Recall@K: {rec_at_k_par:.4f},NDCG@K: {ndcg_at_k_par:.4f}')

RMSE: 0.7086,Precision@K: 0.1346,Recall@K: 1.0000,NDCG@K: 0.9902

In [72]:
def get_top_p_recommendations(df, user_id, p=5):
    user_data = df[df['user_id'] == user_id]

    top_k_items = user_data.sort_values(by='predicted_rating', ascending=False).head(k)
    
    print(f"=== User '{user_id}' Top-{p} Recommendation ===")
    return top_k_items[['item_id', 'predicted_rating', 'actual_rating']]

In [74]:
# Create a comparison dataframe
comparison_df = pd.DataFrame({
    'predicted_rating': mf_pred['rating'].values,
    'actual_rating': mf_test['rating'].values,
    'user_id' : mf_test['user'],
    'item_id' : mf_test['item']
})
comparison_df.head(10)

    predicted_rating  actual_rating     user_id item_id
1           4.618122            5.0         오또잇   서령 본점
3           4.438002            5.0         먹깨비   서령 본점
18          4.469247            5.0          쵸옹   서령 본점
30          4.796223            4.5        콩콩슈슈   서령 본점
40          4.606422            5.0         부자맨   서령 본점
56          3.855541            3.5  matziplist  우래옥 본점
60          4.275736            5.0     배부른라따뚜이  우래옥 본점
74          4.063868            5.0         ysp  우래옥 본점
82          4.158745            5.0      lami88  우래옥 본점
83          3.981681            4.0          뚜띠  우래옥 본점

In [19]:
"""
def ndcg_at_k(y_true, y_score, k=-1): #Vector의 계산으로 이루어짐
    y_true = np.array(y_true)
    y_score = np.array(y_score)
    n = len(y_true)
    # k가 -1 또는 데이터 전체보다 크면 k=n으로 보정
    if k == -1 or k > n:
        k = n

    order = np.argsort(y_score)[::-1]
    y_true_sorted = y_true[order[:k]]  # k 길이만큼만 자름
    dcg = np.sum((2 ** y_true_sorted - 1) / np.log2(np.arange(2, k + 2)))
    best_dcg = np.sum((2 ** np.sort(y_true)[::-1][:k] - 1) / np.log2(np.arange(2, k + 2)))

    return dcg / best_dcg if best_dcg > 0 else 0.0

ndcg_k = []
for i,col in enumerate(R_pred):
    ndcg_k.append(ndcg_at_k(R[i],R_pred[i],k=-1))
print('ndcg@k mean:' , np.mean(ndcg_k))
"""

"\ndef ndcg_at_k(y_true, y_score, k=-1): #Vector의 계산으로 이루어짐\n    y_true = np.array(y_true)\n    y_score = np.array(y_score)\n    n = len(y_true)\n    # k가 -1 또는 데이터 전체보다 크면 k=n으로 보정\n    if k == -1 or k > n:\n        k = n\n\n    order = np.argsort(y_score)[::-1]\n    y_true_sorted = y_true[order[:k]]  # k 길이만큼만 자름\n    dcg = np.sum((2 ** y_true_sorted - 1) / np.log2(np.arange(2, k + 2)))\n    best_dcg = np.sum((2 ** np.sort(y_true)[::-1][:k] - 1) / np.log2(np.arange(2, k + 2)))\n\n    return dcg / best_dcg if best_dcg > 0 else 0.0\n\nndcg_k = []\nfor i,col in enumerate(R_pred):\n    ndcg_k.append(ndcg_at_k(R[i],R_pred[i],k=-1))\nprint('ndcg@k mean:' , np.mean(ndcg_k))\n"

### 2. DeepCoNN

In [12]:
dc_data = data[['user_id','item_id','user_rating','user_query']]
dc_data.columns = ['user_id','item_id','rating','review']

dc_train = dc_data.groupby('user_id').sample(frac=0.8,random_state=42)
dc_train_ind = dc_train.index
dc_test = dc_data.drop(dc_train_ind)

In [13]:
from collections import defaultdict
import random
import os
import torch

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    torch.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    
set_seed(42)

In [14]:
from konlpy.tag import Okt
from tqdm import tqdm
from collections import Counter

jvm_path =r'C:\Program Files\Java\jdk-23\bin\server\jvm.dll'
#os.environ['JAVA_HOME'] = r'C:\Program Files\Java\jdk-23\bin\server\jvm.dll'
os.environ['JAVA_HOME'] = r'C:\Program Files\Java\jdk-25.0.2'


# --- Hyperparam settings ---
MAX_VOCAB_SIZE = 20000  # Top N
MAX_DOC_LENGTH = 550   

def tokeniz(data):
    okt = Okt()
    
    # 1. Construct User-Item document
    user_docs = data.groupby('user_id')['review'].apply(lambda x: ' '.join(map(str, x))).reset_index()
    item_docs = data.groupby('item_id')['review'].apply(lambda x: ' '.join(map(str, x))).reset_index()

    print('Morpheme(형태소) Analysis & Tokenization processing')

    tqdm.pandas(desc='user docs tokenization')
    user_docs['tokenized'] = user_docs['review'].progress_apply(lambda x: okt.morphs(x,stem=True))

    tqdm.pandas(desc='item docs tokenization')
    item_docs['tokenized'] = item_docs['review'].progress_apply(lambda x: okt.morphs(x,stem=True))

    # 2. Tokenization / generate Vocab dictionary
    print("Generating Dict...")
    all_tokens =[]
    for tokens in user_docs['tokenized']:
        all_tokens.extend(tokens)
    for tokens in item_docs['tokenized']:
        all_tokens.extend(tokens)
    word_counts = Counter(all_tokens)

    # 0-<PAD> / 1-<UNK>
    vocab = {'<PAD>': 0, '<UNK>': 1}
    for i, (word, count) in enumerate(word_counts.most_common(MAX_VOCAB_SIZE)):
        vocab[word] = i + 2  # Start from 2

    print(f"Dict size: {len(vocab)}\n")

    return vocab,user_docs,item_docs

# 3. Padding
def text_to_padded_sequence(text, vocab, max_length):
    # 단어가 사전에 없으면 <UNK>(1)로 처리
    seq = [vocab.get(word, vocab['<UNK>']) for word in text]
    
    # Length Adjustment
    if len(seq) > max_length:
        return seq[:max_length] # Truncation
    else:
        return seq + [vocab['<PAD>']] * (max_length - len(seq)) # Padding

tr_vocab,dc_tr_user_doc,dc_tr_item_doc = tokeniz(dc_train)
_,dc_te_user_doc,dc_te_item_doc = tokeniz(dc_test)

# 4. UI sequence
def app_padding(vocab,user_doc,item_doc):
    print("Apply padding and int sequence")
    user_doc['seq'] = user_doc['tokenized'].apply(lambda tokens: text_to_padded_sequence(tokens,vocab,MAX_DOC_LENGTH))
    user_seq_dict = dict(zip(user_doc['user_id'], user_doc['seq']))
    
    
    item_doc['seq'] = item_doc['tokenized'].apply(lambda tokens: text_to_padded_sequence(tokens,vocab,MAX_DOC_LENGTH))
    item_seq_dict = dict(zip(item_doc['item_id'],item_doc['seq']))

    unk_idx = vocab['<UNK>']
    pad_idx = vocab['<PAD>']

    def unk_ratio(sequences):
        all_tokens = [idx for seq in sequences for idx in seq]
        non_pad    = [idx for idx in all_tokens if idx != pad_idx]
        unk_count  = non_pad.count(unk_idx)
        return unk_count / len(non_pad) if non_pad else 0.0
    
    user_unk = unk_ratio(user_doc['seq'])
    item_unk = unk_ratio(item_doc['seq'])
    print(f"[UNK ratio] User docs: {user_unk*100:.2f}% | Item docs: {item_unk*100:.2f}%")
    print(f"           Total Avg: {(user_unk + item_unk) / 2 * 100:.2f}%")
    
    return user_seq_dict,item_seq_dict

tr_user_seq_dict,tr_item_seq_dict = app_padding(tr_vocab,dc_tr_user_doc,dc_tr_item_doc)
te_user_seq_dict,te_item_seq_dict = app_padding(tr_vocab,dc_te_user_doc,dc_te_item_doc)
print("Preprocessing Complete")

Morpheme(형태소) Analysis & Tokenization processing

user docs tokenization: 100%|██████████| 5205/5205 [01:06<00:00, 78.08it/s]
item docs tokenization: 100%|██████████| 353/353 [00:45<00:00,  7.79it/s]

Generating Dict...
Dict size: 13548

Morpheme(형태소) Analysis & Tokenization processing

user docs tokenization: 100%|██████████| 1557/1557 [00:10<00:00, 142.22it/s]
item docs tokenization: 100%|██████████| 334/334 [00:10<00:00, 32.12it/s]

Generating Dict...
Dict size: 6267

Apply padding and int sequence
[UNK ratio] User docs: 0.00% | Item docs: 0.00%
           Total Avg: 0.00%
Apply padding and int sequence
[UNK ratio] User docs: 1.26% | Item docs: 1.22%
           Total Avg: 1.24%
Preprocessing Complete

In [15]:
import torch.nn as nn
from gensim.models import KeyedVectors, Word2Vec

# 1. Load Pre-trained LM (Korean fastText-from Meta)
word2vec_model = KeyedVectors.load_word2vec_format("C:/Users/hanan/Downloads/cc.ko.300.vec.gz",binary=False,limit=300000) #"C:/Users/한승원(hanan)/Downloads/cc.ko.300.vec.gz"

EMBED_DIM = 300 
vocab_size = len(tr_vocab.values()) + 1 # Identical size with Vocab dict

# 2. PyTorch Embedding Layer Weight: (vocab_size, EMBED_DIM)
embedding_matrix = np.zeros((vocab_size, EMBED_DIM))

# 3. 단어 사전(vocab)을 순회하며 가중치 행렬 채우기
for word, idx in tr_vocab.items():
    if word in word2vec_model:
        # 사전 학습된 모델에 단어가 존재하면 해당 벡터를 가져옴
        embedding_matrix[idx] = word2vec_model[word]
    else:
        # OOV (Out of vocab) changed as random dist
        if word == '<PAD>':
            embedding_matrix[idx] = np.zeros(EMBED_DIM)
        else:
            embedding_matrix[idx] = np.random.normal(scale=0.6, size=(EMBED_DIM,))

covered = 0
oov = 0
for word, idx in tr_vocab.items():
    if word in word2vec_model:
        covered += 1
    else:
        oov += 1

print(f"Coverage: {covered}/{len(tr_vocab)} ({covered/len(tr_vocab)*100:.1f}%)")
print(f"OOV: {oov}/{len(tr_vocab)} ({oov/len(tr_vocab)*100:.1f}%)")

# Numpy array -> PyTorch tensor
embedding_tensor = torch.FloatTensor(embedding_matrix)

Coverage: 8460/13548 (62.4%)
OOV: 5088/13548 (37.6%)

In [16]:
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.optim as optim

class DiningCodeDataset(Dataset):
    def __init__(self, df, user_seq_dict, item_seq_dict):
        self.users = df['user_id'].values
        self.items = df['item_id'].values
        self.ratings = df['rating'].values  # Target value
        
        self.user_seq_dict = user_seq_dict
        self.item_seq_dict = item_seq_dict

    def __len__(self):
        return len(self.ratings)

    def __getitem__(self, idx):
        user_id = self.users[idx]
        item_id = self.items[idx]
        rating = self.ratings[idx]

        #
        u_doc = self.user_seq_dict[user_id]
        i_doc = self.item_seq_dict[item_id]

        #
        u_doc_tensor = torch.tensor(u_doc, dtype=torch.long)
        i_doc_tensor = torch.tensor(i_doc, dtype=torch.long)
        rating_tensor = torch.tensor(rating, dtype=torch.float32)

        return u_doc_tensor, i_doc_tensor, rating_tensor

# DataLoader (Batch size: 64)
BATCH_SIZE = 64
tr_dataset = DiningCodeDataset(dc_train, tr_user_seq_dict, tr_item_seq_dict)
tr_dataloader = DataLoader(tr_dataset, batch_size=BATCH_SIZE, shuffle=True)

te_dataset = DiningCodeDataset(dc_test, te_user_seq_dict, te_item_seq_dict)
te_dataloader = DataLoader(te_dataset, batch_size=BATCH_SIZE, shuffle=True)

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class DeepCoNN(nn.Module):
    def __init__(self,config,embedding_matrix):
        super(DeepCoNN,self).__init__()
        self.config = config

        #1.Embedding layer
        vocab_size,embedding_dim = embedding_matrix.shape
        self.user_embedding = nn.Embedding(vocab_size,embedding_dim)
        self.user_embedding.weight = nn.Parameter(
            torch.FloatTensor(embedding_matrix)
        )
        self.user_embedding.weight.requires_grad = True

        #2-1.User Network
        self.user_cnn = nn.Conv1d(
            in_channels=embedding_dim,
            out_channels=config.num_filters,
            kernel_size=config.kernel_size,
            padding=1
        )
        self.user_fc = nn.Linear(config.num_filters,config.latent_dim)

        #2-2. Item Network
        self.item_cnn = nn.Conv1d(
            in_channels=embedding_dim,
            out_channels=config.num_filters,
            kernel_size=config.kernel_size,
            padding=1
        )
        self.item_fc = nn.Linear(config.num_filters,config.latent_dim)

        #Dropout
        self.dropout = nn.Dropout(config.dropout_rate)

        #3.FM Layer (2nd-order latent vectors)
        self.fm_linear = nn.Linear(config.latent_dim*2,1)
        
        self.fm_V = nn.Parameter(
            torch.rand(config.latent_dim*2,config.fm_k)
        )
        self.global_bias = nn.Parameter(torch.zeros(1))

    def forward(self,user_doc,item_doc):
        """
        Args:
            user_doc: (batch_size,max_doc_length)
            item_doc: (batch_size,max_doc_length)

        Returns:
            rating: (batch_size,)
        """

        #User_Net
        user_emb = self.embedding(user_doc) # (B,L,E)
        user_emb = user_emb.transpose(1,2) # (B,E,L) - conv1d input format

        user_conv = F.relu(self.user_cnn(user_emb)) 
        user_pool = F.max_pool1d(user_conv,kernel_size=user_conv.size(2))
        user_pool = user_pool.squeeze(2)

        user_latent = F.relu(self.user_fc(user_pool))
        user_latent = self.dropout(user_latent)

        #item_Net
        item_emb = self.embedding(item_doc) # (B,L,E)
        item_emb = item_emb.transpose(1,2) # (B,E,L) - conv1d input format

        item_conv = F.relu(self.item_cnn(item_emb)) 
        item_pool = F.max_pool1d(item_conv,kernel_size=item_conv.size(2))
        item_pool = item_pool.squeeze(2)

        item_latent = F.relu(self.item_fc(item_pool))
        item_latent = self.dropout(item_latent)

        #concatenate
        z = torch.cat([user_latent,item_latent],dim=1)

        #FM layer
        linear_term = self.fm_linear(z)

        interactions = torch.mm(z,self.fm_V)
        interactions_squared = torch.mm(z**2,self.fm_V**2)

        quadratic_term = 0.5*torch.sum(
            interactions**2-interactions_squared,dim=1,keepdim=True
        )

        #Predict
        rating = self.global_bias + linear_term.squeeze(1) + quadratic_term.squeeze(1)
        
        return rating

class Config:

    max_doc_length = 550
    embedding_dim = 300

    "Model Parameters"
    num_filters = 100
    kernel_size = 3
    latent_dim = 50
    fm_k = 8

    "Training"
    batch_size = 64
    num_epochs = 5
    learning_rate = 0.002
    dropout_rate = 0.5

    "Other"
    device='cuda'
    random_seed=42

In [19]:
import torch.nn as nn
import torch.optim as optim

config = Config()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Current device: {device}")
model = DeepCoNN(config=config, embedding_matrix=embedding_matrix).to(device)


criterion = nn.L1Loss()
optimizer = optim.RMSprop(model.parameters(),alpha=0.9, lr=0.002, weight_decay=1e-8)

Current device: cpu

TypeError: __init__() got an unexpected keyword argument 'embedding_matrix'

In [18]:
EPOCHS = config.num_epochs

for epoch in range(EPOCHS):
    model.train()  
    total_loss = 0.0
    
    for batch_idx, (batch_user, batch_item, batch_rating) in enumerate(tr_dataloader):
    
        batch_user = batch_user.to(device)
        batch_item = batch_item.to(device)
        batch_rating = batch_rating.to(device)
        
        optimizer.zero_grad()
        
        predictions = model(batch_user, batch_item)
        loss = criterion(predictions, batch_rating)
    
        loss.backward()
        
        optimizer.step()
        total_loss += loss.item()
        
        # Progress
        if (batch_idx + 1) % 50 == 0:
            global_step = epoch * len(tr_dataloader) + batch_idx
            print(f"Epoch [{epoch+1}/{EPOCHS}], Step [{batch_idx+1}/{len(tr_dataloader)}], Loss: {loss.item():.4f}")
    avg_loss = total_loss / len(tr_dataloader)
    print(f"==== Epoch {epoch+1} Complete | Avg Loss: {avg_loss:.4f} ====\n")

NameError: name 'config' is not defined

In [24]:
import mlflow
import mlflow.pytorch

mlflow.set_tracking_uri('http://localhost:5000')
mlflow.set_experiment("deep_conn_hybrid")

EPOCHS = config.num_epochs

with mlflow.start_run():
    mlflow.log_params({
        "epochs": EPOCHS,
        "learning_rate": config.learning_rate,
        "batch_size": config.batch_size,
        "max_vocab_size": MAX_VOCAB_SIZE,
        "max_doc_length": MAX_DOC_LENGTH,
    })

    for epoch in range(EPOCHS):
        model.train()  
        total_loss = 0.0
        
        for batch_idx, (batch_user, batch_item, batch_rating) in enumerate(tr_dataloader):
        
            batch_user = batch_user.to(device)
            batch_item = batch_item.to(device)
            batch_rating = batch_rating.to(device)
            
            optimizer.zero_grad()
            
            predictions = model(batch_user, batch_item)
            loss = criterion(predictions, batch_rating)
        
            loss.backward()
            
            optimizer.step()
            total_loss += loss.item()
            
            # Progress
            if (batch_idx + 1) % 50 == 0:
                global_step = epoch * len(tr_dataloader) + batch_idx
                mlflow.log_metric("step_loss", loss.item(), step=global_step)
                print(f"Epoch [{epoch+1}/{EPOCHS}], Step [{batch_idx+1}/{len(tr_dataloader)}], Loss: {loss.item():.4f}")
        avg_loss = total_loss / len(tr_dataloader)
        mlflow.log_metric("avg_train_loss", avg_loss, step=epoch)        
        print(f"==== Epoch {epoch+1} Complete | Avg Loss: {avg_loss:.4f} ====\n")
    
    mlflow.pytorch.log_model(model, "model")

ImportError: cannot import name 'Sentinel' from 'typing_extensions' (c:\Users\hanan\miniconda3\envs\NLP_test\lib\site-packages\typing_extensions.py)

In [56]:
model.eval()
dc_pred = dc_test.copy() 
pred = []

with torch.no_grad():    
    for batch_user, batch_item,_ in te_dataloader:
        
        batch_user = batch_user.to(device)
        batch_item = batch_item.to(device)
        batch_rating = batch_rating.to(device)
        
        batch_preds = model(batch_user,batch_item)
        
        pred.extend(batch_preds.cpu().numpy())
dc_pred['rating'] = pred

In [57]:
dc_test.columns = ['user','item','rating','review']
dc_pred.columns = ['user','item','rating','review']

import sys
sys.path.append('../..')  # Go up two levels to reach the directory containing 'Study'
from Study.RecSys.matrixfactorization.preprocessing import precision_at_k,ndcg_at_k,recall_at_k
from sklearn.metrics import root_mean_squared_error

rmse_par = root_mean_squared_error(dc_pred['rating'].values,dc_test['rating'].values)

prec_at_k_par = precision_at_k(dc_pred,dc_test,k=10)
rec_at_k_par = recall_at_k(dc_pred,dc_test,k=10)
ndcg_at_k_par = ndcg_at_k(dc_pred,dc_test,k=10)

print(f'RMSE: {rmse_par:.4f},Precision@K: {prec_at_k_par:.4f},Recall@K: {rec_at_k_par:.4f}, NDCG@K: {ndcg_at_k_par:.4f}') # Add NDCG

RMSE: 0.8115,Precision@K: 0.1346,Recall@K: 1.0000, NDCG@K: 0.9875

In [58]:
def get_top_p_recommendations(df, user, p=5,input_type=0):
    """
    input_type: 0- user_id / 1- user_name
    """
    if input_type==1:
        user_i = user_n2i[user]
        user_data = df[df['user_id'] == user_i]

        top_k_items = user_data.sort_values(by='predicted_rating', ascending=False).head(p)
        
        print(f"=== User '{user}' Top-{p} Recommendation ===")
        return top_k_items[['item_id', 'predicted_rating', 'actual_rating']]
    else:
        user_n = user_i2n[user]
        user_data = df[df['user_id'] == user]

        top_k_items = user_data.sort_values(by='predicted_rating', ascending=False).head(p)
        
        print(f"=== User '{user_n}' Top-{p} Recommendation ===")
        return top_k_items[['item_id', 'predicted_rating', 'actual_rating']]

# Create a comparison dataframe
comparison_df = pd.DataFrame({
    'predicted_rating': dc_pred['rating'].values,
    'actual_rating': dc_test['rating'].values,
    'user_id' : dc_test['user'],
    'item_id' : dc_test['item'],
    'review' : dc_test['review']
})
comparison_df.head(20)
get_top_p_recommendations(comparison_df,149,p=10,input_type=0)

=== User 'Francis Kim' Top-10 Recommendation ===

Empty DataFrame
Columns: [item_id, predicted_rating, actual_rating]
Index: []

In [59]:
comparison_df

,predicted_rating,actual_rating,user_id,item_id,review
1,4.449809,5.0,3800,158,먹어본 평양냉면 중에 제일 맛있었습니다 다른 곳들은 좀 짜다는 느낌이 강했는데 서령...
3,4.196479,5.0,2638,158,"평양냉면계의 신흥강자, 미슐랭 원스타의 위엄 -육수 한 숟갈부터 압도적인 육향. 메..."
18,4.351213,5.0,4628,158,주말 저녁 오픈 30분 전에 가서 웨이팅 걸었더니 바로 들어감. 평냉 러버 친구한테...
30,4.517001,4.5,4711,158,깔끔하고 맛있는 평냉!! 수육도 너무 맛있어서 꼭 같이 먹어줘야함!! ...
40,4.384190,5.0,3097,158,가격은 평양냉면이라 그런지 조금 있는편\r\n저는 기본 물을 추천드립니다 ...
...,...,...,...,...,...
19283,4.363707,3.0,4205,225,일단 맛있음.\r\n근데 사람이 많아서 그런지 모르겟지만\r\n몇몇 종업원 서비스 ...
19285,4.165748,4.0,2830,225,양갈비와 왕양꼬치 시켰는데 반찬인 참나물과 같이 먹으면 맛있어요
19289,4.478324,4.0,5079,119,맛과 분위기술집이지만 음식 맛이 훌륭합니다. 주문한 요리가 바로바로 나와 따뜻하고 ...
19290,4.159199,5.0,1439,119,꿔바로우가 바삭쫀득하니 너무맛있어요! 남은거포장해서 집에왔는데도 계속바삭이! ...
19293,4.117541,3.0,1500,119,송화양꼬치에서 미향양갈비&양꼬치로 상호명이 바뀌었습니다. 그렇지만 메뉴판은 일부만 ...